on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2

    - name: Set version name
      run: |
        PUBSPEC_VERSION="$(grep -oP 'version: \K.+' pubspec.yaml)"
        VERSION_NAME="${PUBSPEC_VERSION}-${GITHUB_SHA:0:7}"
        echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

    - name: Build APKs
      run: |
        flutter build apk --build-name="$VERSION_NAME" --release --target-platform android-arm,android-arm64 --split-per-abi
        # and rename them
        sudo apt-get install -y rename
        rename 's/app-/inbox-app-/' build/app/outputs/flutter-apk/*.apk

    - name: Upload release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: andelf/nightly-release@main
      with:
        prerelease: false
        tag_name: nightly
        name: ${{ env.VERSION_NAME }}
        files: build/app/outputs/flutter-apk/*.apk

# needed for making releases
permissions:
  contents: write
